
DROP TABLE IF EXISTS cleaned_hospital_data;

-- Create table to store the cleaned hospital dataset with appropriate data types
CREATE TABLE cleaned_hospital_data (
	patient_id INT PRIMARY KEY,
	name VARCHAR(255),
	age INT,
	gender VARCHAR(10),
	blood_type VARCHAR(3),
	medical_condition TEXT,
	date_of_admission DATE,
	doctor VARCHAR(255),
	hospital TEXT,
	insurance_provider VARCHAR(255),
	billing_amount NUMERIC(12,2),
	room_number VARCHAR(10),
	admission_type VARCHAR(20),
	discharge_date DATE,
	medication TEXT,
	test_results TEXT,
	length_of_stay INT
);

-- Load the cleaned dataset exported from Python into PostgreSQL
COPY cleaned_hospital_data 
FROM 'C:\Program Files\PostgreSQL\17\data\cleaned_hospital_data.csv'
DELIMITER ','
CSV HEADER;

-- Check total number of records in the table
SELECT 
	COUNT(*)
FROM cleaned_hospital_data;

-- Preview the first 10 records
SELECT *
FROM cleaned_hospital_data
LIMIT 10;

-- Quick check for missing values in key columns
SELECT 
    COUNT(*) FILTER (WHERE patient_id IS NULL) AS missing_patient_id,
    COUNT(*) FILTER (WHERE date_of_admission IS NULL) AS missing_date,
    COUNT(*) FILTER (WHERE billing_amount IS NULL) AS missing_billing
FROM cleaned_hospital_data;

-- Count of patients by gender
SELECT 
	gender, 
	COUNT(*) AS patients
FROM cleaned_hospital_data
GROUP BY gender
ORDER BY patients;

-- Count of patients by age group
SELECT
CASE
	WHEN age < 18 THEN 'Child'
	WHEN age BETWEEN 18 AND 35 THEN 'Young Adult'
	WHEN age BETWEEN 35 AND 60 THEN 'Adult'
	ELSE 'Senior'
END AS age_group,
	COUNT(*) AS patients
FROM cleaned_hospital_data
GROUP BY age_group
ORDER BY patients;

-- Count of admissions by type (Emergency, Elective, etc.)
SELECT 
	admission_type, 
	COUNT(*) AS admissions
FROM cleaned_hospital_data
GROUP BY admission_type
ORDER BY admissions DESC;

-- Number of admissions per day
SELECT 
    date_of_admission AS day_start,
    COUNT(*) AS admissions
FROM cleaned_hospital_data
GROUP BY day_start
ORDER BY day_start;

-- Number of admissions per week
SELECT 
    DATE_TRUNC('week', date_of_admission)::date AS week_start,
    COUNT(*) AS admissions
FROM cleaned_hospital_data
GROUP BY week_start
ORDER BY week_start;

-- Number of admissions per month
SELECT 
    DATE_TRUNC('month', date_of_admission)::date AS month_start,
    COUNT(*) AS admissions
FROM cleaned_hospital_data
GROUP BY month_start
ORDER BY month_start;

-- Average length of stay by medical condition
SELECT 
	medical_condition, 
	ROUND(AVG(length_of_stay),0) AS avg_stay
FROM cleaned_hospital_data
GROUP BY medical_condition
ORDER BY avg_stay DESC;

-- Top 10 patients with longest stays
SELECT 
	name, 
	medical_condition, 
	length_of_stay
FROM cleaned_hospital_data
ORDER BY length_of_stay DESC
LIMIT 10;

-- Check min, max, average, median length of stay
SELECT 
	MIN(length_of_stay) AS min_los,
	MAX(length_of_stay) AS max_los,
	ROUND(AVG(length_of_stay),0) AS avg_los,
	PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY length_of_stay) AS median_los
FROM cleaned_hospital_data;

-- Total revenue generated by all patients
SELECT 
	SUM(billing_amount) AS total_revenue
FROM cleaned_hospital_data;

-- Revenue by medical condition
SELECT 
	medical_condition,
	SUM(billing_amount) AS revenue
FROM cleaned_hospital_data
GROUP BY medical_condition
ORDER BY revenue DESC;

-- Revenue by insurance provider
SELECT 
	insurance_provider,
	SUM(billing_amount) AS revenue
FROM cleaned_hospital_data
GROUP BY insurance_provider
ORDER BY revenue DESC;

-- Check min, max, average, and median billing amounts
SELECT 
	MIN(billing_amount) As min_bill, 
	MAX(billing_amount) AS max_bill, 
	ROUND(AVG(billing_amount),2) AS avg_bill, 
	PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY billing_amount) AS median_bill
FROM cleaned_hospital_data;

-- Number of patients per hospital
SELECT
	hospital, 
	COUNT(*) AS patients
FROM cleaned_hospital_data
GROUP BY hospital
ORDER BY patients DESC
LIMIT 10;

-- Top 10 doctors by patient count
SELECT
	doctor, 
	COUNT(*) AS patients
FROM cleaned_hospital_data
GROUP BY doctor
ORDER BY patients DESC
LIMIT 10;

